### ISSUE TITLE
WeasyPrint no longer installs

### ISSUE THREAD

**Issue by mrgou** [conda-forge/weasyprint-feedstock#16] opened 2021-01-12 10:56 UTC
Looks like there's an issue with the repo:

```
>conda install weasyprint
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - weasyprint

Current channels:

  - https://conda.anaconda.org/conda-forge/win-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

**Comment by liZe** [comment] 2021-01-12 12:50
Hello!

WeasyPrint’s package is not available for Windows, see https://anaconda.org/conda-forge/weasyprint

So, it’s actually a duplicate of #15!

**Closed by liZe** 2021-01-12 12:50 UTC
